[project]
name = "pure-mjlab-code"
version = "0.1.0"
description = "HLIP + CLF walking task for mjlab"
readme = "README.md"
authors = [
    { name = "CodrinCrismariu", email = "codrincrismariu@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mjlab>=1.0.0",
    "scipy",
]

[project.scripts]
pure-mjlab-code = "pure_mjlab_code:main"

[project.entry-points."mjlab.tasks"]
pure_mjlab_code = "pure_mjlab_code"

[build-system]
requires = ["uv_build>=0.10.6,<0.11.0"]
build-backend = "uv_build"
