"""HLIP + CLF walking task configuration.

This module provides a factory function to create a base HLIP walking task
config. The agent learns to:
  - Track a full-body reference trajectory generated by the HLIP controller.
  - Minimise the CLF value V (converge to the desired orbit).
  - Maintain holonomic constraints on the stance foot.
  - Keep proper gait timing.

Robot-specific configurations call this factory and customise as needed.
"""

import math
from dataclasses import replace

from mjlab.envs import ManagerBasedRlEnvCfg
from mjlab.envs.mdp.actions import JointPositionActionCfg
from mjlab.managers.action_manager import ActionTermCfg
from mjlab.managers.command_manager import CommandTermCfg
from mjlab.managers.curriculum_manager import CurriculumTermCfg
from mjlab.managers.event_manager import EventTermCfg
from mjlab.managers.observation_manager import ObservationGroupCfg, ObservationTermCfg
from mjlab.managers.reward_manager import RewardTermCfg
from mjlab.managers.scene_entity_config import SceneEntityCfg
from mjlab.managers.termination_manager import TerminationTermCfg
from mjlab.scene import SceneCfg
from mjlab.sim import MujocoCfg, SimulationCfg
from mjlab.tasks.hlip import mdp
from mjlab.tasks.hlip.mdp.hlip_command import HLIPCommandCfg
from mjlab.tasks.lip.mdp.joint_lock_action import JointLockActionCfg
from mjlab.terrains import TerrainImporterCfg
from mjlab.utils.noise import UniformNoiseCfg as Unoise
from mjlab.viewer import ViewerConfig


def make_hlip_env_cfg() -> ManagerBasedRlEnvCfg:
  """Create base HLIP + CLF walking task configuration.

  The HLIP task provides:
    - Full-body reference trajectory tracking (CoM, pelvis, swing foot, upper body)
    - CLF-based stability rewards (V, Vdot)
    - Holonomic stance-foot constraint rewards
    - Velocity tracking rewards
    - Standard locomotion regularisation
  """

  ##
  # Observations
  ##

  policy_terms = {
    "base_ang_vel": ObservationTermCfg(
      func=mdp.builtin_sensor,
      params={"sensor_name": "robot/imu_ang_vel"},
      noise=Unoise(n_min=-0.2, n_max=0.2),
    ),
    "projected_gravity": ObservationTermCfg(
      func=mdp.projected_gravity,
      noise=Unoise(n_min=-0.05, n_max=0.05),
    ),
    "joint_pos": ObservationTermCfg(
      func=mdp.joint_pos_rel,
      noise=Unoise(n_min=-0.01, n_max=0.01),
    ),
    "joint_vel": ObservationTermCfg(
      func=mdp.joint_vel_rel,
      noise=Unoise(n_min=-1.0, n_max=1.0),
      scale=0.05,
    ),
    "actions": ObservationTermCfg(func=mdp.last_action),
    "sin_phase": ObservationTermCfg(
      func=mdp.sin_phase,
      params={"command_name": "hlip"},
    ),
    "cos_phase": ObservationTermCfg(
      func=mdp.cos_phase,
      params={"command_name": "hlip"},
    ),
    "contact_state": ObservationTermCfg(
      func=mdp.contact_state,
      params={"sensor_name": "feet_ground_contact"},
    ),
    "ref_traj": ObservationTermCfg(
      func=mdp.ref_traj,
      params={"command_name": "hlip"},
    ),
    "act_traj": ObservationTermCfg(
      func=mdp.act_traj,
      params={"command_name": "hlip"},
    ),
    "ref_traj_vel": ObservationTermCfg(
      func=mdp.ref_traj_vel,
      params={"command_name": "hlip"},
      clip=(-20.0, 20.0),
    ),
    "act_traj_vel": ObservationTermCfg(
      func=mdp.act_traj_vel,
      params={"command_name": "hlip"},
      clip=(-20.0, 20.0),
    ),
  }

  critic_terms = {
    "base_lin_vel": ObservationTermCfg(
      func=mdp.base_lin_vel,
    ),
    "base_ang_vel": ObservationTermCfg(
      func=mdp.base_ang_vel,
    ),
    "root_quat": ObservationTermCfg(
      func=mdp.root_quat_w,
    ),
    "projected_gravity": ObservationTermCfg(
      func=mdp.projected_gravity,
    ),
    "velocity_commands": ObservationTermCfg(
      func=mdp.hlip_velocity_command,
      params={"command_name": "hlip"},
      scale=(2.0, 2.0, 2.0),
    ),
    "joint_pos": ObservationTermCfg(
      func=mdp.joint_pos_rel,
    ),
    "joint_vel": ObservationTermCfg(
      func=mdp.joint_vel_rel,
      scale=0.05,
    ),
    "actions": ObservationTermCfg(func=mdp.last_action),
    "sin_phase": ObservationTermCfg(
      func=mdp.sin_phase,
      params={"command_name": "hlip"},
    ),
    "cos_phase": ObservationTermCfg(
      func=mdp.cos_phase,
      params={"command_name": "hlip"},
    ),
    "contact_state": ObservationTermCfg(
      func=mdp.contact_state,
      params={"sensor_name": "feet_ground_contact"},
    ),
    "ref_traj": ObservationTermCfg(
      func=mdp.ref_traj,
      params={"command_name": "hlip"},
    ),
    "act_traj": ObservationTermCfg(
      func=mdp.act_traj,
      params={"command_name": "hlip"},
    ),
    "ref_traj_vel": ObservationTermCfg(
      func=mdp.ref_traj_vel,
      params={"command_name": "hlip"},
      clip=(-20.0, 20.0),
    ),
    "act_traj_vel": ObservationTermCfg(
      func=mdp.act_traj_vel,
      params={"command_name": "hlip"},
      clip=(-20.0, 20.0),
    ),
  }

  observations = {
    "policy": ObservationGroupCfg(
      terms=policy_terms,
      concatenate_terms=True,
      enable_corruption=True,
      history_length=1,
    ),
    "critic": ObservationGroupCfg(
      terms=critic_terms,
      concatenate_terms=True,
      enable_corruption=False,
      history_length=1,
    ),
  }

  ##
  # Actions
  ##

  actions: dict[str, ActionTermCfg] = {
    "joint_pos": JointPositionActionCfg(
      entity_name="robot",
      actuator_names=(
        ".*_hip_.*", ".*_knee_.*", ".*_ankle_.*",
      ),
      scale=0.5,
      use_default_offset=True,
    ),
    "upper_body_lock": JointLockActionCfg(
      entity_name="robot",
      joint_names=(
        ".*_shoulder_.*", ".*_elbow_.*", ".*_wrist_.*",
        "waist_yaw_.*", "waist_roll_.*", "waist_pitch_.*",
      ),
    ),
  }

  ##
  # Commands
  ##

  commands: dict[str, CommandTermCfg] = {
    "hlip": HLIPCommandCfg(
      entity_name="robot",
      resampling_time_range=(5.0, 15.0),
      foot_body_name=r".*_ankle_roll_link",
      z0=0.67,
      y_nom=0.25,
      gait_half_period=0.4,
      T_ds=0.0,
      z_sw_max=0.1,
      z_sw_min=0.0,
      foot_target_range_y=(0.1, 0.5),
      pelv_pitch_ref=0,
      shoulder_ref=(0.16, 0.0, 0.0),
      elbow_ref=0.1,
      waist_yaw_ref=0.0,
      rel_standing_envs=0.05,
      debug_vis=True,
      ranges=HLIPCommandCfg.Ranges(
        lin_vel_x=(-1.0, 1.0),
        lin_vel_y=(-0.2, 0.2),
        ang_vel_z=(-1.0, 1.0),
      ),
    ),
  }

  ##
  # Events
  ##

  events = {
    "reset_base": EventTermCfg(
      func=mdp.reset_root_state_uniform,
      mode="reset",
      params={
        "pose_range": {
          "x": (-0.5, 0.5),
          "y": (-0.5, 0.5),
          "yaw": (-3.14, 3.14),
        },
        "velocity_range": {},
      },
    ),
    "reset_robot_joints": EventTermCfg(
      func=mdp.reset_joints_by_offset,
      mode="reset",
      params={
        "position_range": (0.0, 0.0),
        "velocity_range": (0.0, 0.0),
        "asset_cfg": SceneEntityCfg("robot", joint_names=".*"),
      },
    ),
    "push_robot": EventTermCfg(
      func=mdp.push_by_setting_velocity,
      mode="interval",
      interval_range_s=(10.0, 15.0),
      params={
        "velocity_range": {
          "x": (-1.0, 1.0),
          "y": (-1.0, 1.0),
          "roll": (-0.4, 0.4),
          "pitch": (-0.4, 0.4),
          "yaw": (-0.4, 0.4),
        },
      },
    ),
    "body_friction": EventTermCfg(
      mode="startup",
      func=mdp.randomize_field,
      domain_randomization=True,
      params={
        "asset_cfg": SceneEntityCfg("robot", geom_names=".*_collision"),
        "operation": "abs",
        "field": "geom_friction",
        "ranges": (0.3, 1.2),
      },
    ),
    "encoder_bias": EventTermCfg(
      mode="startup",
      func=mdp.randomize_encoder_bias,
      params={
        "asset_cfg": SceneEntityCfg("robot", joint_names=".*"),
        "bias_range": (-0.015, 0.015),
      },
    ),
    "base_com": EventTermCfg(
      mode="startup",
      func=mdp.randomize_field,
      domain_randomization=True,
      params={
        "asset_cfg": SceneEntityCfg("robot", body_names=()),  # Set per-robot.
        "operation": "add",
        "field": "body_ipos",
        "ranges": {
          0: (-0.05, 0.05),
          1: (-0.05, 0.05),
          2: (-0.01, 0.01),
        },
      },
    ),
  }

  ##
  # Rewards
  ##

  rewards = {
    # === CLF rewards ===
    "clf_reward": RewardTermCfg(
      func=mdp.clf_reward,
      weight=10.0,
      params={"command_name": "hlip", "max_eta_err": 0.2},
    ),
    "clf_decreasing_condition": RewardTermCfg(
      func=mdp.clf_decreasing_condition,
      weight=-1.0,
      params={
        "command_name": "hlip",
        "alpha": 0.5,
        "eta_max": 0.25,
        "eta_dot_max": 0.3,
      },
    ),
    # === Holonomic constraints ===
    # NOTE: Disabled — planc's holonomic reward functions reference
    # cmd.desired_contact_poses / current_contact_poses / current_contact_vels
    # which do NOT exist on HLIPCommandTerm. This means planc effectively
    # trains WITHOUT holonomic rewards. When these rewards are enabled in
    # mjlab (using stance_foot_pos), they give weight 6.0 for standing
    # still, completely dominating the CLF reward (~0.07) and incentivising
    # the agent to never step.
    "holonomic_constraint": RewardTermCfg(
      func=mdp.holonomic_constraint,
      weight=4.0,
      params={"command_name": "hlip", "z_offset": 0.036},
    ),
    "holonomic_constraint_vel": RewardTermCfg(
      func=mdp.holonomic_constraint_vel,
      weight=2.0,
      params={"command_name": "hlip"},
    ),

    # === Regularisation ===
    "joint_torques_l2": RewardTermCfg(
      func=mdp.joint_torques_l2, weight=-1.0e-5
    ),
    "joint_pos_limits": RewardTermCfg(
      func=mdp.joint_pos_limits, weight=-1.0
    ),
    "action_rate_l2": RewardTermCfg(
      func=mdp.action_rate_l2, weight=-0.01
    ),
  }

  ##
  # Terminations
  ##

  terminations = {
    "time_out": TerminationTermCfg(func=mdp.time_out, time_out=True),
    "fell_over": TerminationTermCfg(
      func=mdp.bad_orientation,
      params={"limit_angle": math.radians(50.0)},
    ),
  }

  ##
  # Assemble and return
  ##

  return ManagerBasedRlEnvCfg(
    scene=SceneCfg(
      terrain=TerrainImporterCfg(
        terrain_type="plane",
      ),
      num_envs=1,
      extent=2.0,
    ),
    observations=observations,
    actions=actions,
    commands=commands,
    events=events,
    rewards=rewards,
    terminations=terminations,
    curriculum={},
    viewer=ViewerConfig(
      origin_type=ViewerConfig.OriginType.ASSET_BODY,
      entity_name="robot",
      body_name="",  # Set per-robot.
      distance=3.0,
      elevation=-5.0,
      azimuth=90.0,
    ),
    sim=SimulationCfg(
      nconmax=35,
      njmax=300,
      mujoco=MujocoCfg(
        timestep=0.005,
        iterations=10,
        ls_iterations=20,
      ),
    ),
    decimation=4,
    episode_length_s=20.0,
  )
