"""HLIP + CLF walking task configuration.

This module provides a factory function to create a base HLIP walking task
config. The agent learns to:
  - Track a full-body reference trajectory generated by the HLIP controller.
  - Minimise the CLF value V (converge to the desired orbit).
  - Maintain holonomic constraints on the stance foot.
  - Keep proper gait timing.

Robot-specific configurations call this factory and customise as needed.
"""

import math

from mjlab.envs import ManagerBasedRlEnvCfg
from mjlab.envs.mdp.actions import JointPositionActionCfg
from mjlab.managers.action_manager import ActionTermCfg
from mjlab.managers.command_manager import CommandTermCfg
from mjlab.managers.event_manager import EventTermCfg
from mjlab.managers.observation_manager import ObservationGroupCfg, ObservationTermCfg
from mjlab.managers.reward_manager import RewardTermCfg
from mjlab.managers.scene_entity_config import SceneEntityCfg
from mjlab.managers.termination_manager import TerminationTermCfg
from mjlab.scene import SceneCfg
from mjlab.sim import MujocoCfg, SimulationCfg
from hlip_clf_g1 import mdp
from hlip_clf_g1.mdp.hlip_command import HLIPCommandCfg
from hlip_clf_g1.mdp.upright_waist_action import UprightWaistActionCfg
from mjlab.terrains import TerrainImporterCfg
from mjlab.utils.noise import UniformNoiseCfg as Unoise
from mjlab.viewer import ViewerConfig


def _make_hlip_command_cfg(
  lin_vel_x: tuple[float, float],
  lin_vel_y: tuple[float, float],
  ang_vel_z: tuple[float, float] = (-0.4, 0.4),
) -> HLIPCommandCfg:
  """Build the default HLIP command term with configurable command ranges."""
  return HLIPCommandCfg(
    entity_name="robot",
    resampling_time_range=(5.0, 15.0),
    foot_body_name=r".*_ankle_roll_link",
    z0=0.67,
    y_nom=0.25,
    T_min=0.45,
    T_max=0.7,
    T_ds=0.0,
    z_sw_max=0.25,
    z_sw_min=0.0,
    foot_target_range_y=(0.2, 0.6),
    pelv_pitch_ref=0,
    shoulder_ref=(0.16, 0.0, 0.0),
    elbow_ref=0.1,
    waist_yaw_ref=0.0,
    rel_standing_envs=0.05,
    mpc_enabled=True,
    mpc_horizon=4,
    mpc_t_candidates=7,
    mpc_w_vel=1.0,
    mpc_w_time=0.45,
    mpc_w_foot=0.05,
    mpc_foot_target_range_x=(-0.35, 0.65),
    mpc_abs_y_min=0.1,
    mpc_abs_y_max=0.6,
    mpc_signed_y_min=0.02,
    mpc_max_step_length=0.85,
    mpc_edge_clearance_distance=0.07,
    mpc_edge_distance_cost=100.0,
    mpc_max_stance_height_delta=0.1,
    mpc_fallback_scales=(1.0, 0.8, 0.6, 0.4, 0.2, 0.0),
    debug_vis=True,
    ranges=HLIPCommandCfg.Ranges(
      lin_vel_x=lin_vel_x,
      lin_vel_y=lin_vel_y,
      ang_vel_z=ang_vel_z,
    ),
  )


def make_hlip_env_cfg() -> ManagerBasedRlEnvCfg:
  """Create base HLIP + CLF walking task configuration.

  The HLIP task provides:
    - Full-body reference trajectory tracking (CoM, pelvis, swing foot, upper body)
    - CLF-based stability rewards (V, Vdot)
    - Holonomic stance-foot constraint rewards
    - Velocity tracking rewards
    - Standard locomotion regularisation
  """

  ##
  # Observations
  ##

  policy_terms = {
    "base_ang_vel": ObservationTermCfg(
      func=mdp.builtin_sensor,
      params={"sensor_name": "robot/imu_ang_vel"},
      noise=Unoise(n_min=-0.2, n_max=0.2),
    ),
    "projected_gravity": ObservationTermCfg(
      func=mdp.projected_gravity,
      noise=Unoise(n_min=-0.05, n_max=0.05),
    ),
    "joint_pos": ObservationTermCfg(
      func=mdp.joint_pos_rel,
      noise=Unoise(n_min=-0.01, n_max=0.01),
    ),
    "joint_vel": ObservationTermCfg(
      func=mdp.joint_vel_rel,
      noise=Unoise(n_min=-1.0, n_max=1.0),
      scale=0.05,
    ),
    "actions": ObservationTermCfg(func=mdp.last_action),
    "sin_phase": ObservationTermCfg(
      func=mdp.sin_phase,
      params={"command_name": "hlip"},
    ),
    "cos_phase": ObservationTermCfg(
      func=mdp.cos_phase,
      params={"command_name": "hlip"},
    ),
    "contact_state": ObservationTermCfg(
      func=mdp.contact_state,
      params={"sensor_name": "feet_ground_contact"},
    ),
    "ref_traj": ObservationTermCfg(
      func=mdp.ref_traj,
      params={"command_name": "hlip"},
    ),
    "act_traj": ObservationTermCfg(
      func=mdp.act_traj,
      params={"command_name": "hlip"},
    ),
    "ref_traj_vel": ObservationTermCfg(
      func=mdp.ref_traj_vel,
      params={"command_name": "hlip"},
      clip=(-20.0, 20.0),
    ),
    "act_traj_vel": ObservationTermCfg(
      func=mdp.act_traj_vel,
      params={"command_name": "hlip"},
      clip=(-20.0, 20.0),
    ),
  }

  critic_terms = {
    "base_lin_vel": ObservationTermCfg(
      func=mdp.base_lin_vel,
    ),
    "base_ang_vel": ObservationTermCfg(
      func=mdp.base_ang_vel,
    ),
    "root_quat": ObservationTermCfg(
      func=mdp.root_quat_w,
    ),
    "projected_gravity": ObservationTermCfg(
      func=mdp.projected_gravity,
    ),
    "velocity_commands": ObservationTermCfg(
      func=mdp.hlip_velocity_command,
      params={"command_name": "hlip"},
      scale=(2.0, 2.0, 2.0),
    ),
    "joint_pos": ObservationTermCfg(
      func=mdp.joint_pos_rel,
    ),
    "joint_vel": ObservationTermCfg(
      func=mdp.joint_vel_rel,
      scale=0.05,
    ),
    "actions": ObservationTermCfg(func=mdp.last_action),
    "sin_phase": ObservationTermCfg(
      func=mdp.sin_phase,
      params={"command_name": "hlip"},
    ),
    "cos_phase": ObservationTermCfg(
      func=mdp.cos_phase,
      params={"command_name": "hlip"},
    ),
    "contact_state": ObservationTermCfg(
      func=mdp.contact_state,
      params={"sensor_name": "feet_ground_contact"},
    ),
    "ref_traj": ObservationTermCfg(
      func=mdp.ref_traj,
      params={"command_name": "hlip"},
    ),
    "act_traj": ObservationTermCfg(
      func=mdp.act_traj,
      params={"command_name": "hlip"},
    ),
    "ref_traj_vel": ObservationTermCfg(
      func=mdp.ref_traj_vel,
      params={"command_name": "hlip"},
      clip=(-20.0, 20.0),
    ),
    "act_traj_vel": ObservationTermCfg(
      func=mdp.act_traj_vel,
      params={"command_name": "hlip"},
      clip=(-20.0, 20.0),
    ),
  }

  observations = {
    "actor": ObservationGroupCfg(
      terms=policy_terms,
      concatenate_terms=True,
      enable_corruption=True,
      history_length=1,
    ),
    "critic": ObservationGroupCfg(
      terms=critic_terms,
      concatenate_terms=True,
      enable_corruption=False,
      history_length=1,
    ),
  }

  ##
  # Actions
  ##

  actions: dict[str, ActionTermCfg] = {
    "joint_pos": JointPositionActionCfg(
      entity_name="robot",
      actuator_names=(".*",),
      scale=0.5,
      use_default_offset=True,
    ),
    "upright_waist": UprightWaistActionCfg(
      entity_name="robot",
      source_action_term="joint_pos",
      source_pitch_action_pattern="waist_pitch_joint",
      source_roll_action_pattern="waist_roll_joint",
      pitch_joint_names=("waist_pitch_joint",),
      roll_joint_names=("waist_roll_joint",),
      action_scale_pitch=0,
      action_scale_roll=0,
      pitch_offset=math.radians(0.0),
      roll_offset=0.0,
      upright_pitch_gain=1.0,
      upright_roll_gain=1.0,
    ),
  }

  ##
  # Commands
  ##

  commands: dict[str, CommandTermCfg] = {
    "hlip": _make_hlip_command_cfg(
      lin_vel_x=(-0.6, 0.6),
      lin_vel_y=(-0.2, 0.2),
    ),
  }

  ##
  # Events
  ##

  events = {
    "reset_base": EventTermCfg(
      func=mdp.reset_root_state_uniform,
      mode="reset",
      params={
        "pose_range": {
          "x": (-0.5, 0.5),
          "y": (-0.5, 0.5),
          "yaw": (-3.14, 3.14),
          "z": (-0.02, -0.02),
        },
        "velocity_range": {},
      },
    ),
    "reset_robot_joints": EventTermCfg(
      func=mdp.reset_joints_by_offset,
      mode="reset",
      params={
        "position_range": (0.0, 0.0),
        "velocity_range": (0.0, 0.0),
        "asset_cfg": SceneEntityCfg("robot", joint_names=".*"),
      },
    ),
    "push_robot": EventTermCfg(
      func=mdp.push_by_setting_velocity,
      mode="interval",
      interval_range_s=(10.0, 15.0),
      params={
        "velocity_range": {
          "x": (-1.0, 1.0),
          "y": (-1.0, 1.0),
          "roll": (-0.4, 0.4),
          "pitch": (-0.4, 0.4),
          "yaw": (-0.4, 0.4),
        },
      },
    ),
    "body_friction": EventTermCfg(
      mode="startup",
      func=mdp.dr.geom_friction,
      params={
        "asset_cfg": SceneEntityCfg("robot", geom_names=".*_collision"),
        "operation": "abs",
        "ranges": (0.3, 1.2),
      },
    ),
    "encoder_bias": EventTermCfg(
      mode="startup",
      func=mdp.dr.encoder_bias,
      params={
        "asset_cfg": SceneEntityCfg("robot", joint_names=".*"),
        "bias_range": (-0.015, 0.015),
      },
    ),
    "base_com": EventTermCfg(
      mode="startup",
      func=mdp.dr.body_ipos,
      params={
        "asset_cfg": SceneEntityCfg("robot", body_names=()),  # Set per-robot.
        "operation": "add",
        "ranges": {
          0: (-0.05, 0.05),
          1: (-0.05, 0.05),
          2: (-0.01, 0.01),
        },
      },
    ),
  }

  ##
  # Rewards
  ##

  rewards = {
    # === CLF rewards ===
    "clf_reward": RewardTermCfg(
      func=mdp.clf_reward,
      weight=10.0,
      params={"command_name": "hlip", "max_eta_err": 0.2},
    ),
    "clf_decreasing_condition": RewardTermCfg(
      func=mdp.clf_decreasing_condition,
      weight=-1.0,
      params={
        "command_name": "hlip",
        "alpha": 0.5,
        "eta_max": 0.25,
        "eta_dot_max": 0.3,
      },
    ),
    # === Holonomic constraints ===
    "holonomic_constraint": RewardTermCfg(
      func=mdp.holonomic_constraint,
      weight=4.0,
      params={"command_name": "hlip", "z_offset": 0.036},
    ),
    "holonomic_constraint_vel": RewardTermCfg(
      func=mdp.holonomic_constraint_vel,
      weight=2.0,
      params={"command_name": "hlip"},
    ),

    # === Regularisation ===
    "joint_torques_l2": RewardTermCfg(
      func=mdp.joint_torques_l2, weight=-1.0e-5
    ),
    "joint_pos_limits": RewardTermCfg(
      func=mdp.joint_pos_limits, weight=-1.0
    ),
    "action_rate_l2": RewardTermCfg(
      func=mdp.action_rate_l2, weight=-0.01
    ),
  }

  ##
  # Terminations
  ##

  terminations = {
    "time_out": TerminationTermCfg(func=mdp.time_out, time_out=True),
    "fell_over": TerminationTermCfg(
      func=mdp.bad_orientation,
      params={"limit_angle": math.radians(50.0)},
    ),
    "pelvis_too_low": TerminationTermCfg(
      func=mdp.pelvis_too_low,
      params={
        "minimum_distance": 0.3, # Adjust if needed
        "pelvis_body_name": "pelvis",
        "foot_body_name": r".*_ankle_roll_link",
      },
    ),
    "foot_height_too_low": TerminationTermCfg(
      func=mdp.foot_height_too_low,
      params={
        "minimum_height": -0.05,
        "foot_body_name": r".*_ankle_roll_link",
      },
    ),
    "mpc_fallback_used": TerminationTermCfg(
      func=mdp.mpc_fallback_used,
      params={
        "command_name": "hlip",
        # Grace period: do not terminate in the first second of an episode so
        # the robot has time to establish a valid gait before the MPC has a
        # fully-populated heightmap and can plan proper footholds.
        "min_episode_time_s": 1.0,
      },
    ),
  }

  ##
  # Assemble and return
  ##

  return ManagerBasedRlEnvCfg(
    scene=SceneCfg(
      terrain=TerrainImporterCfg(
        terrain_type="plane",
      ),
      num_envs=1,
      extent=2.0,
    ),
    observations=observations,
    actions=actions,
    commands=commands,
    events=events,
    rewards=rewards,
    terminations=terminations,
    curriculum={},
    viewer=ViewerConfig(
      origin_type=ViewerConfig.OriginType.ASSET_BODY,
      entity_name="robot",
      body_name="",  # Set per-robot.
      distance=3.0,
      elevation=-5.0,
      azimuth=90.0,
    ),
    sim=SimulationCfg(
      nconmax=35,
      njmax=300,
      mujoco=MujocoCfg(
        timestep=0.005,
        iterations=10,
        ls_iterations=20,
      ),
    ),
    decimation=4,
    episode_length_s=20.0,
  )

def make_hlip_distillation_env_cfg() -> ManagerBasedRlEnvCfg:
  config = make_hlip_env_cfg()
  base_actor_terms = config.observations["actor"].terms
  # Distillation student fuses vector + depth observations with CNN+Transformer.

  ##
  # Observations
  ##

  student_vec_terms = {
    "base_ang_vel": ObservationTermCfg(
      func=mdp.builtin_sensor,
      params={"sensor_name": "robot/imu_ang_vel"},
      noise=Unoise(n_min=-0.04, n_max=0.04),# noise=Unoise(n_min=-0.2, n_max=0.2),
    ),
    "projected_gravity": ObservationTermCfg(
      func=mdp.projected_gravity,
      noise=Unoise(n_min=-0.01, n_max=0.01), # noise=Unoise(n_min=-0.05, n_max=0.05),
    ),
    "velocity_commands": ObservationTermCfg(
      func=mdp.hlip_velocity_command,
      params={"command_name": "hlip"},
      scale=(2.0, 2.0, 2.0),
    ),
    "joint_pos": ObservationTermCfg(
      func=mdp.joint_pos_rel,
      noise=Unoise(n_min=-0.002, n_max=0.002),# noise=Unoise(n_min=-0.01, n_max=0.01),
    ),
    "joint_vel": ObservationTermCfg(
      func=mdp.joint_vel_rel,
      noise=Unoise(n_min=-0.2, n_max=0.2),# noise=Unoise(n_min=-1.0, n_max=1.0),
      scale=0.05,
    ),
    "actions": ObservationTermCfg(func=mdp.last_action),
  }

  head_depth_terms = {
    "depth": ObservationTermCfg(
      func=mdp.depth_camera_sparse_terrain_chw_data,
      params={
        "sensor_name": "head_camera",
        "depth_noise_scale": 0.1,
      },
      clip=(0.0, 10.0),
      delay_hold_prob=1,
      delay_min_lag=2,
      delay_max_lag=4,
    ),
  }

  observations = {
    "student_vec": ObservationGroupCfg(
      terms=student_vec_terms,
      concatenate_terms=True,
      enable_corruption=True,
      history_length=1,
    ),
    "head_camera_depth": ObservationGroupCfg(
      terms=head_depth_terms,
      concatenate_terms=True,
      enable_corruption=True,
      history_length=0,
    ),
    "teacher": ObservationGroupCfg(
      terms=base_actor_terms,  # Keep privileged actor observations from the base config.
      concatenate_terms=True,
      enable_corruption=False,
      history_length=1,
    ),
  }

  config.observations = observations

  config.commands = {
    "hlip": _make_hlip_command_cfg(
      lin_vel_x=(0.0, 0.6),
      lin_vel_y=(0.0, 0.0),
      ang_vel_z=(0.0, 0.0),
    ),
  }
  config.commands["hlip"].mpc_contact_recompute_grace_period_s = 0.4

  return config
